---
language: generic

cache:
  timeout: 600
  directories:
    - $HOME/.stack

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://github.com/TokTok/hs-tools/releases/download/v0.1/hs-tools-v0.1.tar.gz | tar xz -C $HOME

script:
  - hlint .
  - stylish-haskell-lhs -i .
  - git diff --exit-code
  - stack --no-terminal test --coverage
  - shc github-tools testsuite
