language: generic

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

env: CABALVER=1.18 GHCVER=7.8.4
addons: {apt: {packages: [alex-3.1.7, happy-1.19.5, cabal-install-1.18, ghc-7.8.4], sources: [hvr-ghc]}}

install:
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - cabal update

script:
  - CABAL_FLAGS="--enable-tests --enable-benchmarks --enable-library-coverage"
  - cabal install --only-dependencies $CABAL_FLAGS
  - cabal configure $CABAL_FLAGS
  - cabal build
  - cabal test
  - cabal check
