language: haskell
ghc: 7.8

cache:
  directories:
    - $HOME/.cabal
    - $HOME/.ghc

install:
  - cabal update
  - cabal install happy
  - cabal install "aeson < 0.11" github/ --disable-library-profiling
  - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
  - cabal configure --enable-tests --enable-benchmarks --enable-library-coverage
  - cabal build
